### ISSUE TITLE
Add day  of week

### ISSUE THREAD

**Issue by 0ev** [sparcs-kaist/taxi-front#119]
# Summary 

It adds a fuunction that recieves a time and converts it to a string conatining the day  of week

# Tasks 

- [x] moment.js 공부
- [x] Tool/trans.js 에 date2str 함수 만들기
- [x] 기존 독단적인 date변환 함수를 사용하는 컴포넌트들 수정하기
