### ISSUE TITLE
스타일 수정 및 리팩토링

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#134]
# Summary 

피그마와 맞지 않는 스타일들을 수정합니다. 또한 비효율적으로 사용되던 요소들의 리팩토링도 진행합니다.

# Tasks 

- [x] 개설 페이지 : 옵션들
- [x] 내 방 페이지 : 방 아이템 Hover
- [x] 마이 페이지 : 컨테이너 내부 스타일
- [x] 리팩토링 : 방 리스트를 RoomList로 컴포넌트화
- [x] 리팩토링 : 아이콘
