### ISSUE TITLE
마이 페이지 개선

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#138]
# Summary 

스타일 수정 및 코드 리팩토링

# Tasks 

- [ ] 마이 페이지 : 개인 정보 수정 모달
- [ ] 마이 페이지 : 사용 약관 모달
- [ ] 마이 페이지 : 만든 사람들 모달
