### ISSUE TITLE
방 인원 설정

### ISSUE THREAD

**Issue by GrasshopperBears** [sparcs-kaist/taxi-front#160]
# Summary 

방의 최대 인원을 설정합니다.

# Tasks 

- [ ] Counter 컴포넌트 구현
- [ ] 방 생성시 인원 설정
- [ ] 검색 조건에 인원 추가
