### ISSUE TITLE
사진 불러오는 방식 Refactoring

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#161]
# Summary 

기존의 프로필 사진은  user 오브젝트 ID에 s3 주소를 붙여 이미지를 불러왔고
채팅 이미지 또한 메시지의 오브젝트 ID에 s3 주소를 붙여 이미지를 불러왔습니다.
이러한 방식은 back과 AWS관련 환경변수가 통일되어야 한다는 단점이 있고,
dev 환경에서도 S3를 사용하여야 한다는 단점이 있습니다.

# Tasks 

- [ ] 마이페이지 / 프로필 사진 방식 수정
- [ ] 채팅 / 프로필 사진 방식 수정
- [ ] 채팅 / 메시지 이미지 방식 수정
