### ISSUE TITLE
방 검색, 생성 페이지 location 및 현재 시각 back과 동기화

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#166]
# Summary 

방 검색, 생성 페이지 location 및 현재 시각 back과 동기화

# Tasks 

- [x] 방 검색 페이지 location 서버와 동기화
- [ ] 방 검색 페이지 현재 시각 서버와 동기화
- [x] 방 생성 페이지 location 서버와 동기화
- [ ] 방 생성 페이지 현재 시각 서버와 동기화

**Comment by GrasshopperBears** [comment]
시각 동기화는 이후 이슈에서 처리하는 것으로 결정
