### ISSUE TITLE
검색 정렬

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#186]
API를 수정하고 나중에 검색 정렬 이슈에 추가시키는 것이 좋을 것 같습니다!

_Originally posted by @14KGun in https://github.com/sparcs-kaist/taxi-front/pull/183#discussion_r949031696_

# Summary 

검색 결과 정렬을 지원하고 검색 추가 옵션을 추가합니다.

# Tasks 

- [ ] 검색 결과를 정렬할 수 있습니다
- [ ] 추가 옵션에 내가 참여 중인 방 보기를 추가합니다
- [ ] 추가 옵션에 남은 인원이 0명인 방 보기를 추가합니다

**Comment by 14KGun** [comment]
https://github.com/sparcs-kaist/taxi-front/issues/206 와 중복되는 이슈 입니다.
