### ISSUE TITLE
RoomSelectionModal 리팩토링

### ISSUE THREAD

**Issue by GrasshopperBears** [sparcs-kaist/taxi-front#197]
# Summary 

RoomSelectionModal 컴포넌트를 리팩토링합니다.

# Tasks 

- [x] 모달에 transition 적용
- [x] 버튼 깜빡임 해결
- [x] 위 작업을 위해 userId를 global state로 이동. 초기화 중에는 빈 화면 표시.
- [ ] resize 관련 문제 해결
  - 가로 축소할 경우 모달이 사라짐
  - 세로 축소할 경우 스크롤 안됨
- [x] 점선 좌우 padding 수정 (-> 12px)

**Comment by GrasshopperBears** [comment]
@14KGun
점선 padding 관련해서 현재 모달 기본 padding이 15px로 적용되어있는데 15px로 가도 될까요?

**Comment by GrasshopperBears** [comment]
현재 파악하고 있는 문제점
- `Search`에서 `SideResult`를 반환하는 `rightLay`를 매번 새로 반환 => 모바일/데탑 화면 변환시 새로운 `SideResult`가 반환되며 `selectedRoomInfo`가 초기화
- 애니메이션 없는 문제는 원인 파악 중
  - 모바일/데탑 따라 서로 다른 `RoomSelectionModal`을 반환해서, 혹은
  - `RoomSelectionModal` 내 `if (!props?.roomInfo) return <></>;` 때문?

**Comment by GrasshopperBears** [comment]
resize될 때 모달이 닫히는 현상은 이후 별도 이슈에서 처리
