### ISSUE TITLE
Style 하나의 theme 파일로 통합하기

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#229]
# Summary 

현재 파일에서 하드코딩으로 쓰이고 있는 색상들 부터 폰트, 그림자, 크기 등등을 하나의 파일로 통합하여 관리합니다.

# Tasks 

- [x] theme.js에 택시의 스타일 테마를 정립하기
- [ ] 모든 파일들에 적용하기
- [x] 폰트 Roboto로 수정
- [x] 버튼 Component 제작 (모든 곳에서 사용 가능한 방향으로 수정 및 관리 예정 / 우선 Search 화면에 적용)
- [x] 버튼 Click 및 Touch behavior 수정
- [x] Search의 isMobile 코드 수정

**Comment by 14KGun** [comment]
Discussed in https://github.com/sparcs-kaist/taxi-front/discussions/221
