### ISSUE TITLE
Typescript 활성화하기

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#232]
# Summary 

현재 config 파일이 jsconfig에서 tsconfig로 변경이 되어있기는 하지만 세부적인 설정이 완료되지 않아 ts를 사용할수 없는 상태입니다.

# Tasks 

- [x] 필요한 dependency 설치
- [x] eslintrc.json 수정
- [x] prettierrc.json 수정
