### ISSUE TITLE
모든 환경에서의 택시 Icon 수정

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#242]
# Summary 

웹 브라우저, 앱, 웹앱 등의 환경에서의 아이콘 설정이 필요해보임

# Tasks 

- [x] 아이폰 웹앱 아이콘 설정
- [x] favicon 수정
- [x] manifest.json 수정
- [x] index.html 수정
