### ISSUE TITLE
Login page refactoring and styling

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#245]
# Summary 

로그인 페이지의 스타일을 피그마에 맞춰 수정

# Tasks 

- [x] 버튼 수정 및 보완
- [x] 택시 로고 asset으로 만들기
- [x] HeaderBar 컴포넌트 추가
