### ISSUE TITLE
방 개설 페이지 스타일링

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#248]
# Summary 

방 개설 페이지의 컴포넌트 스타일을 피그마와 일치하도록 수정합니다

# Tasks 

- [x] AddRoom을 jsx에서 tsx로 변경
- [x] 옵션 컴포넌트들 스타일 수정 및 theme.ts 적용
- [x] 스타일 수정 과정에서 불필요하게 긴 코드들 모두 제거 및 리팩터링
- [x] `MaxPartLength` 컴포넌트의 이름을 `MaxPeople`로 변경
- [x] `Button.tsx`의 `buttonType` props를 `type`으로 변경
- [x] `WhiteContainer`의 `marginAuto` 디폴트 값을 `false`로 변경
- [x] `theme.ts` 파일에 `zIndex` 추가 (보완 필요)
- [x] `RLayout.Popup`의 스타일을 수정하고 기존에 여러 layer를 씌워서 백그라운드 클릭하던 것을 레이어를 하나로 줄이고 `e.stopPropagation`을 사용
