### ISSUE TITLE
참여 중인 방 5개 이상일 때, 방 참여 제한

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#268]
# Summary 

참여 중인 방이 5개 이상일 때, 검색 페이지에서 방 참여를 제한 합니다.

# Tasks 

- [x] 참여 중인 방을 global state로 관리
- [x] 참여 중인 방 개수가 5개 이상일 때, 검색 페이지에서 방 참여 제한
- [x] 참여 중인 방 개수가 5개 이상일 때, 방 개설 페이지에서 방 참여 제한

**Comment by imYourChoi** [comment]
개설 페이지 작업도 동시에 하면 좋을 것 같습니다

**Comment by 14KGun** [comment]
> 개설 페이지 작업도 동시에 하면 좋을 것 같습니다

생각못했는데, 그래야 하겠네요!!
좋은 것 같습니다 :)
