### ISSUE TITLE
마이 페이지 스타일링

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#272]
# Summary 

마이 페이지에 있는 컴포넌트들의 스타일과 아이콘을 수정합니다.

# Tasks 

- [x] 피그마와 맞지 않는 스타일 수정
- [x] 아이콘 수정
- [x] 클래스 이름 변경 `chat-selectable` -> `selectable`
- [x] `ND` 클래스 제거
- [x] `App.css`에 안쓰이는 코드 제거
- [x] 마이페이지 Hover 및 Touch 수정
