### ISSUE TITLE
마이 페이지에 Modal 컴포넌트 적용

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#277]
# Summary 

마이 페이지에서 Modal 컴포넌트를 사용하지 않는 메뉴들을 사용하도록 수정

# Tasks 

- [x] Modal 컴포넌트 수정
- [x] 메뉴들에 적용 (Ex. 만든 사람들, 수정하기)
- [x] 각종 Modal 컴포넌트 리팩토링 및 스타일링
- [x] Modal의 close 버튼 default 값을 true로 변경
- [x] Modal에 default width 추가
- [x] RLayout.Popup과 useReactiveState를 width 설정 가능하게 변경
