### ISSUE TITLE
error를 recoil로 관리

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#307]
# Summary 

error 페이지로의 이동을 url (`history.push`) 가 아닌 global-state로 페이지를 띄우도록 수정합니다.

 - recoil error state 권장 type
   ```
   {
     message: string, // 사용자에게 보여줄 메시지
     record: Nullable<string>, // null이 아닌 경우, back에 보낼 error 정보
   }
   ```
   ~(back에는 `{ message, url, record, datetime }` 정도의 정보만 전달해줘서 logging하면 되지 않을까 싶습니다.)~
   ~((userInfo, ip)같은 정보는 back에서 따로 처리 후 DB에 push)~
  에러 로깅은 [#342 이슈](https://github.com/sparcs-kaist/taxi-front/issues/342)에서 처리 합니다.

# Tasks 

- [ ] app.js 에서 `<Route exact path="/error/:error" component={Error} />` 제거
- [ ] recoil에 error state 추가
- [ ] `Skeleton`에서 error state 감지 되면, 에러 페이지로의 이동 로직 추가
- [ ] `useTaxiAPI`에서 status code가 200이 아닌 경우, error recoil-state 수정
- [ ] 모든 axios 함수 사용에서 status code가 200이 아닌 경우, error recoil-state 수정
   (이 과정에서 `axios`함수 사용을 `useTaxiAPI`로 대체할 수 있을 경우, 대체합니다.)
