### ISSUE TITLE
RLayout 손보기

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#315]
# Summary 

웹에서 `<Rlayout.R1>`의 크기가 불필요하게 커보여서 조절

# Tasks 

- [x] `<R1>`에서 최대 크기 수정
- [x] `<R2>`의 최대 크기 수정
- [x] `<R2>`에서도 작은 사이즈일 때 `<R1>`을 반환
- [x] 화면이 커질 때 채팅에서 내방으로 이동
