### ISSUE TITLE
Chatting 스타일링

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#324]
# Summary 

채팅의 전체적인 스타일을 수정합니다.

# Tasks 

- [x] 이미지 여백 오류 수정
- [x] 입력창 스타일 수정
- [x] 채팅창 컨테이너 리팩토링
