### ISSUE TITLE
베타 안내창 띄우기

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#365]
# Summary 

베타에 대한 안내문을 Alert Provider를 이용해 띄웁니다.

# Tasks 

- [x] react-cookie 사용
- [x] 하루에 한번 뜨게 적용
- [x] 안내문 작성
- [x] 마이페이지에 메뉴 추가
