### ISSUE TITLE
자잘한 스타일 수정

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#367]
# Summary 

자잘한 스타일들을 수정합니다.

# Tasks 

- [ ] Room 인원 색상
- [ ] 정렬 옵션 및 pagination 크기 및 색상
- [ ] 회색 버튼 hover
