### ISSUE TITLE
방 공유 기능

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#377]
# Summary 

방의 링크를 공유하고 카카오톡에서 방에 관한 정보가 뜰 수 있도록 기능 구현.
<img width="380" alt="Screenshot 2022-11-10 at 3 19 45 PM" src="https://user-images.githubusercontent.com/84715637/201015333-d03120f0-aac8-428e-a78f-e1daedfbb688.png">

# Tasks 

- [ ] 링크 공유 버튼
- [ ] 카톡에 공유시 뜨는 메세지 수정
- [ ] 링크 클릭시 어떤 화면 띄울지 논의

**Comment by 0ev** [comment]
https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation
OG image generation을 사용하면 좋을 것 같아요!

**Comment by 14KGun** [comment]
https://developers.kakao.com/docs/latest/ko/message/js-link

도 참고하면 좋을 것 같습니다 ~
