### ISSUE TITLE
모바일 검색 시 검색 옵션 아래에 결과 뜨도록 수정

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#400]
# Summary 

모바일 검색 페이지에서 검색 시 검색 버튼 아래에 결과가 뜨고 자동으로 스크롤 되도록 수정.

# Tasks 

- [x] `Search` 페이지에서 아래에 뜨도록 수정
- [x] Scroll 관련해서 ScrollRestoration 수정
- [x] 컨테이너의 overflow 속성 수정
- [x] Layout 리팩토링
