### ISSUE TITLE
결제/정산 시에 채팅 메시지 전송

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#435]
# Summary 

사용자가 결제 혹은 정산 시에 자동으로 채팅 메시지를 전송하는 기능을 구현

# Tasks 

- [ ] 결제/정산 메시지 ui 구현
- [ ] 결제/정산 완료 시에 메시지를 보내는 로직 구현
- [ ] 그 과정에서 필요한 리팩토링 진행
