### ISSUE TITLE
Flutter와 이벤트 기반 통신

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#523]
# Summary 

`Flutter`와 이벤트 기반 통신을 합니다.

# Tasks 

- [x] 로그아웃 버튼 클릭시 Flutter에 이벤트 전달
- [x] 세션에 의한 자동 로그아웃시 Flutter에 이벤트 전달
- [x] 알림 설정을 "on"으로 변경하려 할 시 Flutter에 이벤트 전달 및 결과 값 확인
- [x] Alert 모달 띄우는 이벤트 리스너 생성
- [x] 에러 페이지로 이동하는 이벤트 리스너 생성

**Comment by 14KGun** [comment]
@happycastle114 이벤트 더 필요하면 말씀 부탁드립니다. ㅎ
