### ISSUE TITLE
채팅 UI 개선

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#540]
# Summary 

2023/04/24 디자인팀(@yumincho)의 택시 UI 피드백 중 

> 1. 데탑뷰 내 방 보기 페이지에서 채팅창 Header와 내 방 리스트에서 보여지는 정보 겹침
> 2. 모바일 뷰 채팅 페이지 Header에서 햄버거 버튼 보다는 (un)fold 버튼으로 대체되었으면 함
> 3. ModalRoomSelect 컴포넌트에서 탑승자 디자인이 채팅창이랑 다름 (탑승 및 최대 인원/남은 인원/인원 의 용어 통일)

이 있었습니다.

위 3개의 피드백을 따라 UI를 개선합니다.

# Tasks 

 - [ ] `Fullchat`과 유사한 방식으로 작동하도록 `Sidechat` UI 수정
 - [ ] `(un)fold` 버튼으로 바꾸었으나 `(Open/Clsoe)FullscreenRoundedIcon` 와 유사하여 UI 해침, 다른 아이콘으로 수정
 - [ ] i18n으로 용어 통일 및, 공통된 컴포넌트 사용으로 UI 통일
