### ISSUE TITLE
PNPM Migration

### ISSUE THREAD

**Issue by cokia** [sparcs-kaist/taxi-front#588]
# Summary 
23년 여름학기 첫 회의에서 결정된 사항인 PNPM 마이그레이션 작업에 대한 이슈입니다.

# Tasks 
- [ ] NPM 의존성 제거
- [ ] PNPM 셋업
- [ ] gitignore에 package-lock.json 파일 추가
- [ ] PNPM 사용을 강제하는 스크립트 추가
