### ISSUE TITLE
Migrate to monorepo

### ISSUE THREAD

**Issue by SnowSuno** [sparcs-kaist/taxi-front#699]
# Summary 

`pnpm workspace`를 이용한 모노레포 구조로 마이그레이션합니다. 

# Tasks 

- [x] 디렉토리 구조 설정
- [x] pnpm workspace 설정
- [x] 영향 받는 CI/CD 확인 with Sang @withSang
