### ISSUE TITLE
`@taxi/core`, `@taxi/app` 패키지 init

### ISSUE THREAD

**Issue by SnowSuno** [sparcs-kaist/taxi-front#702]
# Summary 

공통 로직 및 ui 컴포넌트를 작성하는 `@taxi/core`와 앱 코드를 작성하는 `@taxi/app` 패키지의 초기 설정을 진행합니다.

# Tasks 

- [x] 신규 패키지 init
	- [x] #710
	- [x] #705
- [x] `@taxi/web`에 `@taxi/core` dependency로 추가 및 빌드 동작 확인
	- [x] `build:app` `build:web` script 추가하고 netlify, Dockerfile에 반영
- [x] sparcs-kaist/biseo#457 에서 monorepo 개선사항 가져와서 반영하기
