### ISSUE TITLE
Taxi app/web 리디자인

### ISSUE THREAD

**Issue by SnowSuno** [sparcs-kaist/taxi-front#711]
# Summary 

코드/디자인 각각에서 두개의 큰 개선이 이루어지는 Long Living Task 입니다. 
- 전반적인 리디자인 및 리브랜딩
- 앱/웹 단일 코드베이스로 마이그레이션

Breaking change가 많은 긴 태스크인 만큼 `redesign` 브랜치에서 따로 작업/테스트합니다. 
> `redesign` 브랜치에서 feature 브랜치로 분기, 기능 구현 후 다시 `redesign` 브랜치로 병합

# Tasks 

> 태스크들을 계속 아래에 추가하면 됩니다. 우측 버튼을 클릭하여 단일 체크박스를 이슈로 전환할 수 있습니다. 

- [ ] #702 
- [ ] `refactor` 브랜치 테스트 및 프리뷰 환경 구성
	- [ ] Web preview 설정 (netlify branch deploys)
	- [ ] App preview 설정 (eas updates)
- [ ] `tamagui`를 이용한 컴포넌트 작성
- [ ] `react-router`(web), `react-navigation`(app) 공통 routing 및 navigation util 구현
- [ ] 리디자인 컴포넌트 반영
	- [ ] Some component...

**Comment by SnowSuno** [comment]
지난 회의에서 말한 리디자인+단일 코드베이스화 관련 태스크들 트래킹할 수 있도록 길게 가져갈 이슈 개설했습니다!

일단은 작은 변경사항들이 꽤 생길 것 같아 코멘트로 기록 남길 수 있도록 이슈로 개설했고, 나중에 필요에 따라 github milestone으로 옮겨서 트래킹해도 될 것 같습니다. @14KGun
