### ISSUE TITLE
이벤트 Hook, Atom 수정

### ISSUE THREAD

**Issue by predict-woo** [sparcs-kaist/taxi-front#723]
# Summary 

It implements [This function](https://www.notion.so/sparcs/Hook-Atom-1e0495fa113b45659ba70282be65bf78?pvs=4)

# Tasks 

- [ ] Read previous code
- [ ] Fix event hooks
- [ ] Fix event atoms
