### ISSUE TITLE
프로필 이미지 클릭 시 신고 모달 띄우기

### ISSUE THREAD

**Issue by jyjy1229** [sparcs-kaist/taxi-front#757]
# Summary 

채팅방에서 유저 프로필 이미지 클릭 시 신고 모달 띄우도록 수정

# Tasks 

- [x] 클릭 이벤트 생성
- [ ] 사용자 선택 문구 제외
- [ ] 클릭한 프로필의 유저만 선택된 상태로 모달 띄우기
