### ISSUE TITLE
회원 탈퇴 구현

### ISSUE THREAD

**Issue by jinhyeonkwon** [sparcs-kaist/taxi-front#805]
# Summary 

It implements ...

# Tasks 

- [x] 백엔드에서 `authorId`, `authorName`, `authorProfile`이 `null`로 넘어오는 경우 대응
- [ ] 탈퇴 회원의 경우 신고 기능 작동하지 않도록 수정
- [ ] 채팅방 내부 신고하기 버튼에서 탈퇴 회원 제외
- [ ] 탈퇴 버튼 구현
